Repository fkie-cad/FACT_core, pull requests merged in 2018-07, with the labels that each got.

#130 Skip normal executables
  src/plugins/unpacking/sevenz/code/sevenz.py
  src/plugins/unpacking/sevenz/test/test_plugin_sevenz.py
  src/plugins/unpacking/sfx/__init__.py
  src/plugins/unpacking/sfx/code/__init__.py
  src/plugins/unpacking/sfx/code/sfx.py
  src/plugins/unpacking/sfx/test/__init__.py
  src/plugins/unpacking/sfx/test/data/test_elf_normal
  src/plugins/unpacking/sfx/test/data/test_elf_sfx
  src/plugins/unpacking/sfx/test/data/test_pe_sfx
  src/plugins/unpacking/sfx/test/data/test_rsrc
  src/plugins/unpacking/sfx/test/test_sfx.py
  src/unpacker/unpack.py
Labels: enhancement

#134 Pre analysis bug
  src/helperFunctions/object_storage.py
  src/objects/file.py
  src/scheduler/Analysis.py
  src/storage/db_interface_backend.py
  src/test/acceptance/test_regression_virtual_file_path.py
  src/test/data/regression_one
  src/test/data/regression_two
  src/test/integration/scheduler/test_cycle_with_tags.py
  src/test/unit/helperFunctions/test_object_storage.py
Labels: bug

#124 75 plugin dropdown
  src/bootstrap/bootstrap_common.sh
  src/config/main.cfg
  src/scheduler/Analysis.py
  src/test/acceptance/test_analyze_firmware.py
  src/test/common_helper.py
  src/test/unit/scheduler/test_analysis.py
  src/test/unit/web_interface/test_app_upload.py
  src/web_interface/components/jinja_filter.py
  src/web_interface/templates/upload/upload.html
Labels: feature, gui

#136 Refactoring and test coverage
  src/analysis/YaraPluginBase.py
  src/bootstrap/fact_env.sh
  src/compare/compare.py
  src/helperFunctions/dataConversion.py
  src/helperFunctions/fileSystem.py
  src/helperFunctions/hash.py
  src/helperFunctions/yara_binary_search.py
  src/plugins/analysis/strings/code/strings.py
  src/plugins/analysis/users_and_passwords/internal/update_password_list.py
  src/plugins/compare/file_coverage/code/file_coverage.py
  src/plugins/unpacking/xerox/internal/dsk_container.py
  src/storage/db_interface_admin.py
  src/storage/db_interface_backend.py
  src/storage/db_interface_common.py
  src/storage/db_interface_frontend.py
  src/test/unit/helperFunctions/test_data_conversion.py
  src/unpacker/unpackBase.py
  src/web_interface/components/additional_functions/hex_dump.py
  src/web_interface/components/database_routes.py
  src/web_interface/components/miscellaneous_routes.py
Labels: enhancement

#138 Specify counter in tests
  src/scheduler/Analysis.py
  src/test/acceptance/base.py
  src/test/acceptance/rest/test_rest_analyze_firmware.py
  src/test/acceptance/rest/test_rest_compare.py
  src/test/acceptance/test_analyze_firmware.py
  src/test/acceptance/test_compare_firmwares.py
  src/test/acceptance/test_misc.py
  src/test/integration/scheduler/test_unpack_analyse_and_compare.py
  src/test/integration/scheduler/test_unpack_and_analyse.py
  src/test/unit/scheduler/test_analysis.py
Labels: refactoring

#135 104 add firmware module meta data field
  src/compare/compare.py
  src/helperFunctions/mongo_task_conversion.py
  src/helperFunctions/object_conversion.py
  src/objects/firmware.py
  src/storage/db_interface_backend.py
  src/storage/db_interface_common.py
  src/storage/db_interface_frontend.py
  src/test/acceptance/rest/test_rest_analyze_firmware.py
  src/test/acceptance/rest/test_rest_compare.py
  src/test/acceptance/test_analyze_firmware.py
  src/test/acceptance/test_compare_firmwares.py
  src/test/acceptance/test_misc.py
  src/test/common_helper.py
  src/test/integration/storage/test_db_interface.py
  src/test/integration/storage/test_db_interface_frontend.py
  src/test/integration/web_interface/rest/test_rest_firmware.py
  src/test/unit/helperFunctions/test_mongo_task_conversion.py
  src/test/unit/helperFunctions/test_object_conversion.py
  src/test/unit/objects/test_firmware.py
  src/test/unit/storage/test_db_interface_common.py
  src/test/unit/web_interface/rest/test_rest_firmware.py
  src/test/unit/web_interface/test_app_jinja_filter.py
  src/test/unit/web_interface/test_app_re_analyze.py
  src/test/unit/web_interface/test_app_upload.py
  src/web_interface/components/jinja_filter.py
  src/web_interface/templates/about.html
  src/web_interface/templates/database/database_browse.html
  src/web_interface/templates/generic_view/firmware_detail_tabular_field.html
  src/web_interface/templates/home.html
  src/web_interface/templates/show_analysis.html
  src/web_interface/templates/upload/re-analyze.html
  src/web_interface/templates/upload/upload.html
Labels: enhancement

#141 Fix bug in plugin presets
  src/plugins/compare/file_coverage/code/file_coverage.py
  src/plugins/compare/file_coverage/test/test_plugin_file_coverage.py
  src/storage/db_interface_compare.py
  src/test/integration/scheduler/test_unpack_analyse_and_compare.py
  src/test/unit/compare/test_compare.py
  src/web_interface/templates/upload/upload.html
Labels: bug, refactoring

#143 132 delete intercom bug
  src/intercom/back_end_binding.py
  src/storage/fs_organizer.py
  src/test/acceptance/test_upload_analyze_delete_firmware.py
  src/test/integration/intercom/test_backend_scheduler.py
  src/test/unit/storage/test_fs_organizer.py
  src/web_interface/templates/about.html
Labels: bug

#93 Pre install
  README.md
  src/bootstrap/pre_install.sh
Labels: enhancement

#147 Radare connector
  install.py
  src/bootstrap/bootstrap_frontend.sh
  src/bootstrap/pre_install.sh
  src/bootstrap/radare/Dockerfile
  src/bootstrap/radare/docker-compose.yml
  src/bootstrap/radare/install.sh
  src/bootstrap/radare/nginx/Dockerfile
  src/bootstrap/radare/nginx/nginx.conf
  src/config/main.cfg
  src/config/nginx.conf
  src/helperFunctions/config.py
  src/helperFunctions/web_interface.py
  src/start_fact_frontend.py
  src/test/acceptance/test_io_routes.py
  src/test/unit/helperFunctions/test_web_interface.py
  src/web_interface/components/io_routes.py
  src/web_interface/templates/about.html
  src/web_interface/templates/show_analysis.html
Labels: feature, gui

#148 added exeception handling for decoding error
  src/helperFunctions/parsing.py
  src/plugins/analysis/crypto_material/test/data/error.der
  src/plugins/analysis/crypto_material/test/data/pkcs_fp.file
  src/plugins/analysis/crypto_material/test/data/ssl_fp.file
  src/plugins/analysis/crypto_material/test/test_plugin_crypto_material.py
Labels: bug
