Repository fkie-cad/FACT_core, pull requests merged in 2018-04, with the labels that each got.

#87 Analysis tag scheduler
  src/helperFunctions/ccp_tresholds.py
  src/helperFunctions/tag.py
  src/objects/file.py
  src/plugins/analysis/crypto_material/code/crypto_material.py
  src/plugins/analysis/crypto_material/test/test_plugin_crypto_material.py
  src/plugins/analysis/crypto_material/view/crypto_material.html
  src/scheduler/Analysis.py
  src/scheduler/analysis_tag.py
  src/start_fact_backend.py
  src/storage/db_interface_backend.py
  src/storage/db_interface_common.py
  src/test/data/container/with_key.7z
  src/test/integration/scheduler/test_cycle_with_tags.py
  src/test/integration/storage/test_db_interface_backend.py
  src/test/unit/helperFunctions/test_tag.py
  src/test/unit/scheduler/test_analysis_tag.py
  src/test/unit/web_interface/test_filter.py
  src/web_interface/components/jinja_filter.py
  src/web_interface/filter.py
  src/web_interface/templates/analysis_plugins/generic.html
  src/web_interface/templates/show_analysis.html
Labels: enhancement

#92 new software signatures added
  src/plugins/analysis/software_components/signatures/crypto.yara
  src/plugins/analysis/software_components/signatures/os.yara
  src/plugins/analysis/software_components/signatures/software.yara
  src/plugins/analysis/software_components/signatures/uefi.yara
  src/plugins/analysis/software_components/test/data/software_component_test_list.txt
Labels: analysis, enhancement

#91 88 exploit mitigation bug fixed
  src/helperFunctions/statistic.py
  src/statistic/update.py
  src/test/integration/statistic/test_update.py
  src/test/unit/helperFunctions/test_statistic.py
Labels: bug

#95 show admin options if logged in as admin only
  src/helperFunctions/web_interface.py
  src/test/acceptance/test_analyze_firmware.py
  src/test/unit/helperFunctions/test_web_interface.py
  src/web_interface/components/analysis_routes.py
  src/web_interface/templates/show_analysis.html
Labels: gui

#81 New geouri
  src/helperFunctions/merge_generators.py
  src/plugins/analysis/ip_and_uri_finder/code/ip_and_uri_finder.py
  src/plugins/analysis/ip_and_uri_finder/install.sh
  src/plugins/analysis/ip_and_uri_finder/test/test_ip_and_uri_finder.py
  src/plugins/analysis/ip_and_uri_finder/view/ip_and_uri_finder.html
  src/statistic/update.py
Labels: analysis, enhancement
