Repository fkie-cad/FACT_core, pull requests merged in 2019-05, with the labels that each got.

#252 fixing bug regarding blacklist of analysis
  src/scheduler/Analysis.py
Labels: bug, under review

#254 fix issue 250: root uid is lost when pressing self
  src/test/acceptance/test_upload_analyze_delete_firmware.py
  src/web_interface/components/ajax_routes.py
  src/web_interface/templates/show_analysis.html
Labels: bug, review requested

#257 fix issue 255 yaml.load deprecation warning
  src/helperFunctions/mongo_config_parser.py
Labels: review requested
