Repository fkie-cad/FACT_core, pull requests merged in 2019-10, with the labels that each got.

#293 290 lief api fix
  src/helperFunctions/hash.py
  src/plugins/analysis/elf_analysis/code/elf_analysis.py
  src/test/data/test_executable
  src/test/unit/helperFunctions/test_hash.py
Labels: bug, review requested

#292 fixed issue with missing unpacker data and added regression test
  src/storage/db_interface_frontend.py
  src/test/integration/storage/test_db_interface_frontend.py
Labels: bug, review requested

#296 contiki signature added
  src/plugins/analysis/software_components/signatures/os.yara
  src/plugins/analysis/software_components/test/data/software_component_test_list.txt
  src/web_interface/templates/about.html
Labels: analysis, enhancement

#298 pep8 -> flake8 and pylint errors
  pytest.ini
  src/helperFunctions/plugin.py
  src/helperFunctions/statistic.py
  src/install/common.py
  src/install/db.py
  src/intercom/common_mongo_binding.py
  src/plugins/analysis/strings/code/strings.py
  src/test/unit/analysis/test_plugin_base.py
  src/test/unit/helperFunctions/test_tag.py
  src/test/unit/helperFunctions/test_uid.py
  src/test/unit/helperFunctions/test_yara.py
  src/test/unit/web_interface/security/test_user_role_db_interface.py
  src/web_interface/components/database_routes.py
Labels: refactoring
