Repository fkie-cad/FACT_core, pull requests merged in 2019-02, with the labels that each got.

#202 add real fix
  src/scheduler/Analysis.py
  src/storage/db_interface_common.py
  src/test/unit/scheduler/test_analysis.py
Labels: bug

#211 temporary fix. downgrade modkit from latest commit
  src/install/backend.py
Labels: bug

#212 raw extractor added
  src/mime/custom_mime_raw
  src/plugins/unpacking/raw/__init__.py
  src/plugins/unpacking/raw/code/__init__.py
  src/plugins/unpacking/raw/code/raw.py
  src/plugins/unpacking/raw/install.sh
  src/plugins/unpacking/raw/test/__init__.py
  src/plugins/unpacking/raw/test/data/raw.bin
  src/plugins/unpacking/raw/test/test_raw.py
Labels: feature, unpacking

#213 Sd 269 hp unpacker
  src/plugins/unpacking/hp/__init__.py
  src/plugins/unpacking/hp/code/__init__.py
  src/plugins/unpacking/hp/code/pjl.py
  src/plugins/unpacking/hp/code/update_stream.py
  src/plugins/unpacking/hp/install.sh
  src/plugins/unpacking/hp/internal/__init__.py
  src/plugins/unpacking/hp/internal/pjl_helper.py
  src/plugins/unpacking/hp/test/__init__.py
  src/plugins/unpacking/hp/test/data/hp_container.pjl
  src/plugins/unpacking/hp/test/data/hp_new_container.pjl
  src/plugins/unpacking/hp/test/data/update_stream.bin
  src/plugins/unpacking/hp/test/test_pjl.py
  src/plugins/unpacking/hp/test/test_pjl_helper.py
  src/plugins/unpacking/hp/test/test_update_stream.py
Labels: enhancement, unpacking

#214 installation refactored
  src/compile_custom_magic.py
  src/install/backend.py
Labels: enhancement

#216 replaced internal mime logic by library
  src/compile_custom_magic.py
  src/helperFunctions/fileSystem.py
  src/install/backend.py
  src/install/common.py
  src/mime/custom_mime_archives
  src/mime/custom_mime_bootloader
  src/mime/custom_mime_compressed_streams
  src/mime/custom_mime_drone
  src/mime/custom_mime_file_systems
  src/mime/custom_mime_firmware_containers
  src/mime/custom_mime_internal
  src/mime/custom_mime_linux
  src/mime/custom_mime_lzma
  src/mime/custom_mime_printer
  src/mime/custom_mime_raw
  src/mime/custom_mime_uefi
  src/plugins/analysis/base64_decoder/code/base64_decoder.py
  src/plugins/analysis/file_type/code/file_type.py
  src/plugins/analysis/qemu_exec/code/qemu_exec.py
  src/plugins/unpacking/generic_fs/code/generic_fs.py
  src/scheduler/Analysis.py
  src/test/unit/helperFunctions/test_file_system.py
  src/unpacker/unpack.py
  src/unpacker/unpackBase.py
Labels: refactoring
