Repository fkie-cad/FACT_core, pull requests merged in 2019-11, with the labels that each got.

#306 pull latest docker container before build to avoid dependency issues
  src/plugins/analysis/input_vectors/install.sh
Labels: bug, review requested

#311 Refactoring 2
  src/analysis/PluginBase.py
  src/helperFunctions/binwalk.py
  src/helperFunctions/compare_sets.py
  src/helperFunctions/dataConversion.py
  src/helperFunctions/merge_generators.py
  src/helperFunctions/yara.py
  src/plugins/analysis/binwalk/code/binwalk.py
  src/plugins/analysis/binwalk/test/test_plugin_binwalk.py
  src/test/unit/analysis/test_plugin_base.py
  src/test/unit/helperFunctions/test_binwalk.py
  src/test/unit/helperFunctions/test_compare_sets.py
  src/test/unit/helperFunctions/test_data_conversion.py
  src/test/unit/helperFunctions/test_merge_generators.py
  src/test/unit/helperFunctions/test_yara.py
Labels: refactoring, under review

#312 none functional pip pinning removed and pylint errors corrected
  src/helperFunctions/install.py
  src/install/frontend.py
Labels: refactoring, review requested

#314 moved test code to test folder
  src/helperFunctions/config.py
  src/helperFunctions/fileSystem.py
  src/plugins/analysis/binwalk/test/test_plugin_binwalk.py
  src/plugins/analysis/elf_analysis/test/test_plugin_elf_analysis.py
  src/plugins/analysis/file_system_metadata/test/test_file_system_metadata_routes.py
  src/plugins/analysis/file_type/test/test_plugin_file_type.py
  src/plugins/analysis/linter/test/test_source_code_analysis.py
  src/plugins/analysis/qemu_exec/test/test_plugin_qemu_exec.py
  src/plugins/analysis/qemu_exec/test/test_routes.py
  src/plugins/analysis/software_components/test/test_plugin_software_components_signatures.py
  src/plugins/analysis/tlsh/test/test_plugin_tlsh.py
  src/test/acceptance/auth_base.py
  src/test/acceptance/rest/test_rest_compare.py
  src/test/acceptance/test_compare_firmwares.py
  src/test/acceptance/test_misc.py
  src/test/acceptance/test_upload_analyze_delete_firmware.py
  src/test/common_helper.py
  src/test/integration/common.py
  src/test/integration/intercom/test_backend_scheduler.py
  src/test/integration/intercom/test_intercom_common.py
  src/test/integration/intercom/test_intercom_delete_file.py
  src/test/integration/intercom/test_task_communication.py
  src/test/integration/scheduler/test_cycle_with_tags.py
  src/test/integration/scheduler/test_regression_virtual_file_path.py
  src/test/integration/scheduler/test_unpack_analyse_and_compare.py
  src/test/integration/scheduler/test_unpack_and_analyse.py
  src/test/integration/scheduler/test_unpack_only.py
  src/test/integration/statistic/test_update.py
  src/test/integration/statistic/test_work_load.py
  src/test/integration/storage/test_binary_service.py
  src/test/integration/storage/test_db_interface.py
  src/test/integration/storage/test_db_interface_admin.py
  src/test/integration/storage/test_db_interface_backend.py
  src/test/integration/storage/test_db_interface_compare.py
  src/test/integration/storage/test_db_interface_frontend.py
  src/test/integration/storage/test_db_interface_frontend_editing.py
  src/test/integration/storage/test_db_interface_view_sync.py
  src/test/integration/web_interface/rest/base.py
  src/test/unit/analysis/analysis_plugin_test_class.py
  src/test/unit/analysis/test_yara_plugin_base.py
  src/test/unit/compare/test_compare.py
  src/test/unit/helperFunctions/test_config.py
  src/test/unit/helperFunctions/test_file_system.py
  src/test/unit/helperFunctions/test_hash.py
  src/test/unit/helperFunctions/test_program_setup.py
  src/test/unit/helperFunctions/test_web_interface.py
  src/test/unit/helperFunctions/test_yara_binary_search.py
  src/test/unit/objects/test_file.py
  src/test/unit/objects/test_firmware.py
  src/test/unit/scheduler/test_analysis.py
  src/test/unit/scheduler/test_analysis_tag.py
  src/test/unit/scheduler/test_unpack.py
  src/test/unit/unpacker/test_tar_repack.py
  src/test/unit/unpacker/test_unpacker.py
  src/test/unit/web_interface/base.py
  src/test/unit/web_interface/rest/conftest.py
  src/test/unit/web_interface/test_app_user_management_routes.py
  src/test/unit/web_interface/test_plugin_routes.py
  src/test/yara_signature_testing.py
Labels: refactoring
