Repository fkie-cad/FACT_core, pull requests merged in 2019-07, with the labels that each got.

#253 Single file analysis task
  src/intercom/back_end_binding.py
  src/intercom/common_mongo_binding.py
  src/intercom/front_end_binding.py
  src/scheduler/Analysis.py
  src/start_fact_backend.py
  src/test/acceptance/base.py
  src/test/common_helper.py
  src/test/integration/intercom/test_backend_scheduler.py
  src/test/integration/intercom/test_task_communication.py
  src/test/integration/scheduler/test_cycle_with_tags.py
  src/test/integration/scheduler/test_regression_virtual_file_path.py
  src/test/integration/scheduler/test_unpack_analyse_and_compare.py
  src/test/integration/scheduler/test_unpack_and_analyse.py
  src/test/unit/scheduler/test_analysis.py
  src/test/unit/web_interface/test_app_show_analysis.py
  src/web_interface/components/analysis_routes.py
  src/web_interface/templates/about.html
  src/web_interface/templates/show_analysis.html
Labels: feature, gui, review requested

#274 authentication test fixed
  src/test/acceptance/test_authenticated_gui.py
Labels: bug, review requested

#271 Added statistics endpoint for rest
  .pre-commit-config.yaml
  src/test/acceptance/rest/test_rest_statistic.py
  src/test/common_helper.py
  src/test/unit/web_interface/rest/conftest.py
  src/test/unit/web_interface/rest/test_rest_status.py
  src/web_interface/rest/rest_base.py
  src/web_interface/rest/rest_statistic.py
  src/web_interface/templates/about.html
Labels: rest api, review requested

#281 Fix #279
  src/scheduler/Analysis.py
  src/test/unit/scheduler/test_analysis.py
Labels: bug, refactoring, review requested

#280 Fix broken cwe_checker plugin
  src/plugins/analysis/cwe_checker/code/cwe_checker.py
  src/plugins/analysis/cwe_checker/install.sh
  src/plugins/analysis/cwe_checker/test/test_cwe_checker.py
Labels: under review

#276 Support beta pdf report
  src/helperFunctions/pdf.py
  src/install/frontend.py
  src/test/acceptance/test_io_routes.py
  src/test/integration/helperFunctions/__init__.py
  src/test/integration/helperFunctions/test_pdf.py
  src/test/unit/helperFunctions/test_pdf.py
  src/web_interface/components/io_routes.py
  src/web_interface/templates/show_analysis.html
Labels: feature, review requested
