Repository fkie-cad/FACT_core, pull requests merged in 2019-01, with the labels that each got.

#188 several codacy issues fixed
  src/compare/PluginBase.py
  src/helperFunctions/compare_sets.py
  src/install/radare/Dockerfile
  src/install/radare/nginx/Dockerfile
  src/plugins/unpacking/tpl/code/TPWRN702N.py
Labels: enhancement

#192 plugin detection validity check added
  src/helperFunctions/plugin.py
  src/test/data/plugin_system/none_valid_plugin/no_code_in_here
Labels: bug

#201 Elf analysis plugin
  src/config/main.cfg
  src/plugins/analysis/elf_analysis/__init__.py
  src/plugins/analysis/elf_analysis/code/__init__.py
  src/plugins/analysis/elf_analysis/code/elf_analysis.py
  src/plugins/analysis/elf_analysis/install.sh
  src/plugins/analysis/elf_analysis/internal/__init__.py
  src/plugins/analysis/elf_analysis/internal/matching_template.json
  src/plugins/analysis/elf_analysis/test/__init__.py
  src/plugins/analysis/elf_analysis/test/test_plugin_elf_analysis.py
  src/plugins/analysis/elf_analysis/view/elf_analysis.html
  src/test/unit/web_interface/test_filter.py
  src/web_interface/components/jinja_filter.py
  src/web_interface/filter.py
Labels: analysis, feature
