Repository fkie-cad/FACT_core, pull requests merged in 2019-04, with the labels that each got.

#228 Refactoring and test coverage
  .pre-commit-config.yaml
  pytest.ini
  src/helperFunctions/dataConversion.py
  src/plugins/compare/file_coverage/code/file_coverage.py
  src/scheduler/Compare.py
  src/storage/db_interface_compare.py
  src/test/common_helper.py
  src/test/integration/scheduler/test_unpack_analyse_and_compare.py
  src/test/integration/storage/test_db_interface_compare.py
  src/test/unit/helperFunctions/test_data_conversion.py
  src/test/unit/scheduler/test_compare.py
  src/web_interface/components/ajax_routes.py
  src/web_interface/components/compare_routes.py
  src/web_interface/components/io_routes.py
  src/web_interface/rest/rest_compare.py
Labels: refactoring

#233 Fix authentication test
  src/install/frontend.py
  src/test/acceptance/test_authenticated_gui.py
Labels: bug

#234 proposed changes for better stability of plugin
  src/config/main.cfg
  src/plugins/analysis/cwe_checker/code/cwe_checker.py
  src/plugins/analysis/cwe_checker/test/test_cwe_checker.py
Labels: refactoring

#242 improved standard configuration
  src/config/main.cfg
Labels: refactoring

#245 Qemu exec stability improvements
  src/install/backend.py
  src/plugins/analysis/qemu_exec/code/qemu_exec.py
  src/plugins/analysis/qemu_exec/docker/Dockerfile
  src/plugins/analysis/qemu_exec/docker/start_binary.py
  src/plugins/analysis/qemu_exec/docker/start_binary.sh
  src/plugins/analysis/qemu_exec/routes/ajax_view.html
  src/plugins/analysis/qemu_exec/test/data/other_architectures/test_arm_static
  src/plugins/analysis/qemu_exec/test/data/other_architectures/test_ppc_static
  src/plugins/analysis/qemu_exec/test/test_plugin_qemu_exec.py
  src/plugins/analysis/qemu_exec/test/test_routes.py
  src/web_interface/templates/about.html
Labels: under review
