Repository fkie-cad/FACT_core, pull requests merged in 2019-12, with the labels that each got.

#315 improved test coverage + refactoring
  src/helperFunctions/install.py
  src/objects/file.py
  src/plugins/analysis/init_systems/code/init_system.py
  src/plugins/analysis/init_systems/test/test_plugin_init_system.py
  src/plugins/compare/file_coverage/code/file_coverage.py
  src/storage/db_interface_compare.py
  src/test/integration/storage/test_db_interface_compare.py
  src/test/unit/analysis/test_plugin_base.py
  src/test/unit/helperFunctions/test_hash.py
  src/test/unit/helperFunctions/test_install.py
  src/test/unit/helperFunctions/test_process.py
  src/test/unit/objects/test_file.py
  src/test/unit/web_interface/test_filter.py
  src/web_interface/components/ajax_routes.py
  src/web_interface/filter.py
Labels: refactoring

#317 287 support additional distros
  .gitignore
  README.md
  src/install.py
  src/install/common.py
  src/install/db.py
  src/install/frontend.py
  src/install/pre_install.sh
  src/plugins/analysis/file_type/test/test_plugin_file_type.py
  src/plugins/analysis/qemu_exec/code/qemu_exec.py
  src/plugins/analysis/users_and_passwords/install.sh
  src/start_fact_frontend.py
  src/test/integration/storage/test_binary_service.py
  src/test/unit/unpacker/test_tar_repack.py
  src/test/unit/web_interface/test_filter.py
  src/web_interface/templates/about.html
Labels: enhancement

#319 Refactor check exceptions
  src/analysis/PluginBase.py
  src/helperFunctions/debug.py
  src/helperFunctions/logging.py
  src/helperFunctions/parsing.py
  src/helperFunctions/process.py
  src/scheduler/Analysis.py
  src/scheduler/Compare.py
  src/scheduler/Unpacking.py
  src/test/unit/helperFunctions/test_process.py
Labels: refactoring

#322 connect to moved to helperFunctions.database and fixed some pylint is…
  src/helperFunctions/database.py
  src/helperFunctions/web_interface.py
  src/helperFunctions/yara_binary_search.py
  src/intercom/back_end_binding.py
  src/plugins/analysis/file_system_metadata/code/file_system_metadata.py
  src/plugins/analysis/file_system_metadata/routes/routes.py
  src/plugins/analysis/file_system_metadata/test/test_file_system_metadata_routes.py
  src/plugins/analysis/qemu_exec/routes/routes.py
  src/plugins/analysis/tlsh/code/tlsh.py
  src/plugins/base.py
  src/test/acceptance/test_upload_analyze_delete_firmware.py
  src/test/integration/intercom/test_intercom_delete_file.py
  src/test/integration/scheduler/test_unpack_analyse_and_compare.py
  src/test/integration/scheduler/test_unpack_and_analyse.py
  src/test/unit/analysis/analysis_plugin_test_class.py
  src/test/unit/scheduler/test_analysis.py
  src/test/unit/web_interface/base.py
  src/test/unit/web_interface/rest/conftest.py
  src/web_interface/components/ajax_routes.py
  src/web_interface/components/analysis_routes.py
  src/web_interface/components/compare_routes.py
  src/web_interface/components/database_routes.py
  src/web_interface/components/io_routes.py
  src/web_interface/components/jinja_filter.py
  src/web_interface/components/miscellaneous_routes.py
  src/web_interface/components/statistic_routes.py
  src/web_interface/rest/rest_binary.py
  src/web_interface/rest/rest_binary_search.py
  src/web_interface/rest/rest_compare.py
  src/web_interface/rest/rest_file_object.py
  src/web_interface/rest/rest_firmware.py
  src/web_interface/rest/rest_statistic.py
Labels: bug, refactoring
