Repository fkie-cad/FACT_core, pull requests merged in 2020-04, with the labels that each got.

#377 added parameters to rest responses and tested it (+pylint)
  src/helperFunctions/object_conversion.py
  src/test/unit/helperFunctions/test_object_conversion.py
Labels: feature request, review requested

#381 fixed varietyjs installation bug
  src/install/common.py
Labels: bug

#383 Sd 979 inverse advanced fw search
  src/storage/db_interface_frontend.py
  src/test/acceptance/test_advanced_search.py
  src/test/common_helper.py
  src/web_interface/components/database_routes.py
  src/web_interface/templates/database/database_advanced_search.html
  src/web_interface/templates/database/database_browse.html
Labels: feature

#386 Bugfix inverted search result count
  src/storage/db_interface_frontend.py
  src/test/acceptance/test_advanced_search.py
  src/test/integration/storage/test_db_interface_frontend.py
  src/web_interface/components/database_routes.py
Labels: bug

#384 Sd 955 missing analyses rest endpoint
  src/test/common_helper.py
  src/test/integration/web_interface/rest/test_rest_missing_analyses.py
  src/test/unit/web_interface/rest/test_rest_missing.py
  src/web_interface/rest/rest_base.py
  src/web_interface/rest/rest_missing_analyses.py
  src/web_interface/templates/about.html
Labels: feature

#388 added error handling for missing singature files
  src/analysis/PluginBase.py
  src/analysis/YaraPluginBase.py
  src/start_fact.py
  src/start_fact_backend.py
Labels: changes requested

#385 Sd 965 inverse firmware search rest
  src/helperFunctions/rest.py
  src/storage/db_interface_frontend.py
  src/test/common_helper.py
  src/test/unit/helperFunctions/test_rest.py
  src/test/unit/web_interface/rest/test_rest_binary.py
  src/test/unit/web_interface/rest/test_rest_firmware.py
  src/web_interface/rest/rest_file_object.py
  src/web_interface/rest/rest_firmware.py
Labels: rest api, review requested

#389 Software signatures improved and added
  src/plugins/analysis/software_components/code/software_components.py
  src/plugins/analysis/software_components/signatures/http_server.yara
  src/plugins/analysis/software_components/signatures/lib.yara
  src/plugins/analysis/software_components/signatures/os.yara
  src/plugins/analysis/software_components/test/data/software_component_test_list.txt
Labels: analysis, enhancement, review requested

#391 fixed fs_metadata bug with localization
  src/plugins/analysis/file_system_metadata/code/file_system_metadata.py
Labels: bug

#394 fixed jstree reinstall bug
  src/install/frontend.py
Labels: bug

#398 fixed start all components bug
  src/start_fact.py
Labels: bug

#401 added critical summary suffix + test
  src/plugins/analysis/cve_lookup/code/cve_lookup.py
  src/plugins/analysis/cve_lookup/test/test_cve_lookup.py
Labels: enhancement, under review

#399 removed uninteresting keys from variety result
  src/update_variety_data.py
Labels: enhancement

#405 fix installation issue
  src/install/frontend.py
Labels: bug, review requested

#406 Experimental webinterface fail feedback
  src/analysis/PluginBase.py
  src/objects/file.py
  src/scheduler/Analysis.py
  src/test/unit/scheduler/test_analysis.py
  src/web_interface/components/analysis_routes.py
  src/web_interface/templates/analysis_plugins/fail.html
  src/web_interface/templates/show_analysis.html
Labels: enhancement

#410 fix navbar link area
  src/web_interface/templates/base.html
Labels: gui, under review

#409 ubuntu 20.04 support
  README.md
  src/install.py
  src/install/common.py
  src/install/pre_install.sh
  src/web_interface/templates/about.html
Labels: changes requested, enhancement

#403 Analysis header redesign
  src/storage/db_interface_frontend.py
  src/test/acceptance/test_compare_firmwares.py
  src/test/acceptance/test_upload_analyze_delete_firmware.py
  src/test/common_helper.py
  src/test/integration/storage/test_db_interface_frontend.py
  src/test/integration/web_interface/test_filter.py
  src/test/unit/web_interface/test_filter.py
  src/web_interface/components/ajax_routes.py
  src/web_interface/components/jinja_filter.py
  src/web_interface/filter.py
  src/web_interface/templates/compare/compare.html
  src/web_interface/templates/error.html
  src/web_interface/templates/generic_view/collapsed_list.html
  src/web_interface/templates/generic_view/file_object_macros.html
  src/web_interface/templates/generic_view/general_information.html
  src/web_interface/templates/generic_view/nice_fo_list.html
  src/web_interface/templates/show_analysis.html
Labels: gui

#407 firmware analysis status
  src/intercom/back_end_binding.py
  src/scheduler/Analysis.py
  src/test/integration/intercom/test_backend_scheduler.py
  src/test/unit/scheduler/test_analysis.py
  src/web_interface/templates/system_health.html
Labels: feature

#408 added error passing out of plugin install scripts
  src/plugins/analysis/binwalk/install.sh
  src/plugins/analysis/crypto_hints/install.sh
  src/plugins/analysis/cwe_checker/install.sh
  src/plugins/analysis/elf_analysis/install.sh
  src/plugins/analysis/input_vectors/install.sh
  src/plugins/analysis/ip_and_uri_finder/install.sh
  src/plugins/analysis/linter/install.sh
  src/plugins/analysis/oms/install.sh
  src/plugins/analysis/qemu_exec/install.sh
  src/plugins/analysis/users_and_passwords/install.sh
Labels: changes requested
