Repository fkie-cad/FACT_core, pull requests merged in 2020-05, with the labels that each got.

#412 SD-1045 unsupported hash type bug fixed
  src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
  src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
  src/plugins/analysis/users_and_passwords/view/users_and_passwords.html
Labels: bug, review requested

#413 Sd1047 failed analysis version check bugfix
  src/scheduler/Analysis.py
  src/test/unit/scheduler/test_analysis.py
Labels: bug

#414 converted lists to list groups
  src/web_interface/templates/base.html
  src/web_interface/templates/database/database_browse.html
  src/web_interface/templates/generic_view/firmware_detail_tabular_field.html
  src/web_interface/templates/home.html
Labels: gui

#411 System health redesign
  src/scheduler/Analysis.py
  src/statistic/work_load.py
  src/test/acceptance/test_misc.py
  src/test/common_helper.py
  src/web_interface/rest/rest_statistic.py
  src/web_interface/templates/show_analysis.html
  src/web_interface/templates/system_health.html
Labels: enhancement, gui, review requested

#419 linux 5.x kernel detection
  src/plugins/analysis/software_components/signatures/os.yara
Labels: enhancement, review requested
