Repository fkie-cad/FACT_core, pull requests merged in 2020-02, with the labels that each got.

#330 ReFACToring 2
  src/plugins/analysis/hash/code/hash.py
  src/scheduler/Compare.py
Labels: bug

#327 Cve plugin
  .gitignore
  src/plugins/analysis/cve_lookup/__init__.py
  src/plugins/analysis/cve_lookup/code/__init__.py
  src/plugins/analysis/cve_lookup/code/cve_lookup.py
  src/plugins/analysis/cve_lookup/install.sh
  src/plugins/analysis/cve_lookup/internal/__init__.py
  src/plugins/analysis/cve_lookup/internal/data_parsing.py
  src/plugins/analysis/cve_lookup/internal/database_interface.py
  src/plugins/analysis/cve_lookup/internal/helper_functions.py
  src/plugins/analysis/cve_lookup/internal/setup_repository.py
  src/plugins/analysis/cve_lookup/test/__init__.py
  src/plugins/analysis/cve_lookup/test/test_cve_lookup.py
  src/plugins/analysis/cve_lookup/test/test_data_parsing.py
  src/plugins/analysis/cve_lookup/test/test_database_interface.py
  src/plugins/analysis/cve_lookup/test/test_helper_functions.py
  src/plugins/analysis/cve_lookup/test/test_resources/nvdcve_test_cve_update.json
  src/plugins/analysis/cve_lookup/test/test_resources/test_cpe_extract.xml
  src/plugins/analysis/cve_lookup/test/test_resources/test_cpe_update.xml
  src/plugins/analysis/cve_lookup/test/test_resources/test_cve_extract.json
  src/plugins/analysis/cve_lookup/test/test_resources/test_meta.json
  src/plugins/analysis/cve_lookup/test/test_setup_repository.py
  src/plugins/analysis/cve_lookup/view/cve_lookup.html
  src/web_interface/templates/about.html
Labels: analysis, enhancement, feature

#342 file tree bugfix + refactoring
  src/helperFunctions/file_tree.py
  src/storage/db_interface_frontend.py
  src/test/integration/storage/test_db_interface_frontend.py
  src/test/unit/helperFunctions/test_file_tree.py
  src/web_interface/components/ajax_routes.py
Labels: bug, refactoring

#346 hotfix for 345 and deprecation warning for base64 plug-in
  src/install/backend.py
  src/plugins/analysis/base64_decoder/code/base64_decoder.py
  src/plugins/analysis/base64_decoder/install.sh
  src/web_interface/templates/about.html
Labels: bug, review requested

#349 SD-873 fix yara rule formating bug
  src/web_interface/components/database_routes.py
Labels: bug, gui, review requested

#348 SD-889 Backdoor String detection
  src/plugins/analysis/known_vulnerabilities/signatures/vulnerabilities.yara
  src/plugins/analysis/known_vulnerabilities/test/test_known_vulnerabilities.py
Labels: analysis, review requested

#350 removed hex dump button and code
  src/plugins/compare/file_header/code/file_header.py
  src/plugins/compare/file_header/test/test_file_header.py
  src/test/acceptance/test_io_routes.py
  src/test/unit/web_interface/test_additional_functions.py
  src/web_interface/components/additional_functions/hex_dump.py
  src/web_interface/components/io_routes.py
  src/web_interface/templates/about.html
  src/web_interface/templates/generic_view/hex_dump_popup.html
  src/web_interface/templates/show_analysis.html
Labels: review requested

#343 Refactoring 2
  src/web_interface/templates/show_analysis.html
Labels: refactoring

#356 file tree speed-up
  src/storage/db_interface_frontend.py
  src/web_interface/components/ajax_routes.py
Labels: enhancement

#355 Removed base64 decoder plugin
  src/helperFunctions/dataConversion.py
  src/helperFunctions/strings.py
  src/plugins/analysis/base64_decoder/__init__.py
  src/plugins/analysis/base64_decoder/code/__init__.py
  src/plugins/analysis/base64_decoder/code/base64_decoder.py
  src/plugins/analysis/base64_decoder/install.sh
  src/plugins/analysis/base64_decoder/internal/__init__.py
  src/plugins/analysis/base64_decoder/internal/optimized_word_list.txt
  src/plugins/analysis/base64_decoder/test/__init__.py
  src/plugins/analysis/base64_decoder/test/data/base64.test
  src/plugins/analysis/base64_decoder/test/test_plugin_base64_decoder.py
  src/plugins/analysis/base64_decoder/view/base64_decoder.html
  src/test/acceptance/test_io_routes.py
  src/test/unit/helperFunctions/test_strings.py
  src/web_interface/components/io_routes.py
Labels: review requested

#358 fixed bug in cve_lookup
  src/plugins/analysis/cve_lookup/code/cve_lookup.py
  src/plugins/analysis/cve_lookup/internal/helper_functions.py
  src/plugins/analysis/cve_lookup/test/test_cve_lookup.py
Labels: bug

#360 summary removed from view
  src/plugins/analysis/elf_analysis/view/elf_analysis.html
Labels: analysis

#361 fix view of ip-and-uri-finder
  src/plugins/analysis/ip_and_uri_finder/view/ip_and_uri_finder.html
Labels: analysis, bug
