Repository fkie-cad/FACT_core, pull requests merged in 2020-11, with the labels that each got.

#505 fix insufficient info bug
  src/objects/file.py
  src/test/unit/objects/test_file.py
Labels: bug

#507 Sd1240 plugin doc js
  docsrc/conf.py
  docsrc/modules/helperFunctions.mongo_config_parser.rst
  docsrc/modules/helperFunctions.rst
  src/helperFunctions/debug.py
  src/helperFunctions/hash.py
  src/helperFunctions/mongo_config_parser.py
  src/storage/db_interface_frontend.py
  src/test/unit/helperFunctions/test_debug.py
  src/test/unit/helperFunctions/test_hash.py
  src/test/unit/web_interface/test_database_structure.py
  src/web_interface/components/compare_routes.py
  src/web_interface/components/database_routes.py
  src/web_interface/database_structure.py
  src/web_interface/pagination.py
Labels: docs, refactoring

#508 Linter linguist
  src/plugins/analysis/file_type/view/file_type.html
  src/plugins/analysis/linter/code/source_code_analysis.py
  src/plugins/analysis/linter/install.sh
  src/plugins/analysis/linter/test/test_source_code_analysis.py
  src/plugins/analysis/linter/view/source_code_analysis.html
Labels: feature

#510 1299: Correctly render YARA search queries
  src/web_interface/components/database_routes.py
  src/web_interface/components/jinja_filter.py
  src/web_interface/filter.py
  src/web_interface/templates/database/database_browse.html
Labels: bug, review requested

#511 1239: Added docstrings to install helper and moved crypto helper
  docsrc/modules/helperFunctions.install.rst
  docsrc/modules/helperFunctions.rst
  src/helperFunctions/install.py
  src/install/backend.py
  src/plugins/analysis/crypto_material/code/crypto_material.py
  src/plugins/analysis/crypto_material/internal/__init__.py
  src/plugins/analysis/crypto_material/internal/key_parser.py
  src/test/unit/helperFunctions/test_install.py
Labels: docs, review requested

#515 no more sanitize db duplicate entries
  src/storage/db_interface_admin.py
  src/storage/db_interface_common.py
  src/test/integration/storage/test_db_interface.py
Labels: bug

#513 Orphaned objects
  src/storage/db_interface_frontend.py
  src/test/common_helper.py
  src/test/integration/storage/test_db_interface_frontend.py
  src/test/integration/web_interface/rest/test_rest_missing_analyses.py
  src/test/unit/web_interface/test_app_missing_analyses.py
  src/web_interface/components/miscellaneous_routes.py
  src/web_interface/rest/rest_missing_analyses.py
  src/web_interface/templates/find_missing_analyses.html
Labels: feature

#516 fixed user/pw tag
  src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
  src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
Labels: bug

#517 Sd1240 plugin doc js
  docsrc/conf.py
  docsrc/modules/helperFunctions.rst
  docsrc/modules/helperFunctions.web_interface.rst
  src/helperFunctions/web_interface.py
  src/test/unit/helperFunctions/test_web_interface.py
  src/test/unit/web_interface/test_app_jinja_filter.py
  src/test/unit/web_interface/test_io_routes.py
  src/web_interface/components/io_routes.py
  src/web_interface/components/jinja_filter.py
Labels: docs
