Repository fkie-cad/FACT_core, pull requests merged in 2020-01, with the labels that each got.

#325 Match script identifier over whole command line call to fix shutdown.…
  .isort.cfg
  src/helperFunctions/program_setup.py
Labels: bug

#329 added examples and object structure
  src/web_interface/templates/database/database_advanced_search.html
Labels: gui

#326 760: rm upgrade autoremove and clean from install scripts
  INSTALL.md
  src/helperFunctions/install.py
  src/install/common.py
Labels: refactoring, review requested

#328 crypto hints plug-in added
  .gitignore
  src/plugins/analysis/crypto_hints/__init__.py
  src/plugins/analysis/crypto_hints/code/__init__.py
  src/plugins/analysis/crypto_hints/code/crypto_hints.py
  src/plugins/analysis/crypto_hints/install.sh
  src/plugins/analysis/crypto_hints/test/__init__.py
  src/plugins/analysis/crypto_hints/test/data/CRC32_table
  src/plugins/analysis/crypto_hints/test/test_crypto_hints.py
  src/plugins/analysis/crypto_hints/view/crypto_hints.html
  src/web_interface/templates/about.html
  src/web_interface/templates/analysis_plugins/generic.html
Labels: analysis, enhancement, feature, review requested
