Repository fkie-cad/FACT_core, pull requests merged in 2020-03, with the labels that each got.

#362 Experimental format string resolver
  src/helperFunctions/docker.py
  src/plugins/analysis/input_vectors/code/input_vectors.py
  src/plugins/analysis/qemu_exec/code/qemu_exec.py
  src/plugins/analysis/qemu_exec/test/test_plugin_qemu_exec.py
  src/plugins/analysis/software_components/code/software_components.py
  src/plugins/analysis/software_components/docker/Dockerfile
  src/plugins/analysis/software_components/docker/ghidra_scripts/format_string_version.py
  src/plugins/analysis/software_components/install.sh
  src/plugins/analysis/software_components/internal/resolve_version_format_string.py
  src/plugins/analysis/software_components/signatures/network.yara
  src/plugins/analysis/software_components/test/data/format_string_arm-linux-gnueabihf
  src/plugins/analysis/software_components/test/data/signatures/test_signature.yara
  src/plugins/analysis/software_components/test/data/signatures/test_signatures_wo_meta.yara
  src/plugins/analysis/software_components/test/test_plugin_software_components_signatures.py
  src/plugins/analysis/software_components/test/test_resolve_version_format_string.py
  src/plugins/analysis/software_components/test/test_scan_signatures.py
Labels: analysis, enhancement

#371 Added check for enum34, update copyright strings
  src/compile_yara_signatures.py
  src/install.py
  src/install/pre_install.sh
  src/start_fact_backend.py
  src/start_fact_db.py
  src/update_statistic.py
  src/update_variety_data.py
  src/version.py
  src/web_interface/templates/about.html
Labels: enhancement

#374 thunder-lock activated and cve_lookup set as default plug-in
  src/config/main.cfg
  src/start_fact_frontend.py
Labels: enhancement, review requested

#368 365 update statistics bugfix
  src/statistic/update.py
  src/storage/db_interface_frontend.py
Labels: changes requested

#373 Sd 871 known password tag
  src/plugins/analysis/users_and_passwords/code/password_file_analyzer.py
  src/plugins/analysis/users_and_passwords/test/test_plugin_password_file_analyzer.py
  src/plugins/analysis/users_and_passwords/view/users_and_passwords.html
  src/storage/db_interface_view_sync.py
  src/test/unit/web_interface/test_filter.py
  src/web_interface/components/jinja_filter.py
  src/web_interface/filter.py
Labels: analysis, enhancement, refactoring, review requested

#367 Experimental find failed analyses
  src/helperFunctions/web_interface.py
  src/install/frontend.py
  src/storage/db_interface_frontend.py
  src/test/integration/storage/test_db_interface_frontend.py
  src/test/unit/helperFunctions/test_web_interface.py
  src/test/unit/web_interface/base.py
  src/test/unit/web_interface/test_app_missing_analyses.py
  src/web_interface/components/miscellaneous_routes.py
  src/web_interface/templates/base.html
  src/web_interface/templates/find_missing_analyses.html
Labels: changes requested

#364 added analysis active indicator
  src/analysis/PluginBase.py
  src/helperFunctions/process.py
  src/scheduler/Analysis.py
  src/scheduler/Unpacking.py
  src/test/acceptance/rest/test_rest_statistic.py
  src/test/unit/scheduler/test_unpack.py
  src/web_interface/templates/system_health.html
Labels: discussion needed

#372 Sd 896 yara search show firmware
  src/storage/db_interface_common.py
  src/storage/db_interface_frontend.py
  src/storage/db_interface_frontend_editing.py
  src/test/acceptance/base_full_start.py
  src/test/acceptance/test_binary_search.py
  src/test/acceptance/test_compare_firmwares.py
  src/test/acceptance/test_upload_analyze_delete_firmware.py
  src/test/common_helper.py
  src/test/integration/storage/test_db_interface_frontend_editing.py
  src/test/unit/web_interface/test_app_binary_search.py
  src/web_interface/components/database_routes.py
  src/web_interface/templates/database/database_binary_search.html
  src/web_interface/templates/database/database_binary_search_results.html
  src/web_interface/templates/database/database_browse.html
Labels: analysis, changes requested, enhancement, feature

#376 Fix XSS bug by escaping user input when updating firmware details
  src/helperFunctions/mongo_task_conversion.py
Labels: under review
