Repository fkie-cad/FACT_core, pull requests merged in 2020-08, with the labels that each got.

#466 pdf report bugfixes
  src/test/common_helper.py
Labels: bug

#463 Pie charts
  src/helperFunctions/web_interface.py
  src/install/frontend.py
  src/test/unit/web_interface/test_filter.py
  src/web_interface/filter.py
  src/web_interface/static/js/fact_statistics.js
  src/web_interface/templates/macros.html
  src/web_interface/templates/show_statistic.html
Labels: enhancement

#467 improved unpacking stats
  src/statistic/update.py
Labels: enhancement

#470 Sd425 helper sphinx docs
  .gitignore
  docs/index.md
  docsrc/Makefile
  docsrc/_static/css/custom.css
  docsrc/conf.py
  docsrc/doc_dependencies.txt
  docsrc/images/01_main.png
  docsrc/images/02_upload.png
  docsrc/images/03_firmware_view.png
  docsrc/images/04_users_and_passwords.png
  docsrc/images/05_cve_lookup.png
  docsrc/images/06_binwalk.png
  docsrc/images/07_qemu_exec.png
  docsrc/images/08_compare.png
  docsrc/images/09_system.png
  docsrc/images/10_user_management.png
  docsrc/images/11_advanced_search_result.png
  docsrc/images/12_yara_search.png
  docsrc/images/FACT_Vulnerability_Hunting.png
  docsrc/index.rst
  docsrc/main.rst
  docsrc/modules/helperFunctions.rst
  docsrc/modules/helperFunctions.uid.rst
  src/helperFunctions/uid.py
Labels: feature

#471 added autodoc dependencies to docs
  .github/workflows/deploy_docs.yml
  docsrc/autodoc_dependencies.txt
Labels: bug

#472 added dependency mocks & switched to built-in type hint doc
  .github/workflows/deploy_docs.yml
  docsrc/autodoc_dependencies.txt
  docsrc/conf.py
  docsrc/doc_dependencies.txt
Labels: bug

#475 Sd1239 plugin doc vd
  docsrc/conf.py
  docsrc/modules/helperFunctions.pdf.rst
  docsrc/modules/helperFunctions.rst
  src/helperFunctions/pdf.py
  src/test/integration/helperFunctions/test_pdf.py
  src/test/unit/helperFunctions/test_pdf.py
  src/web_interface/components/io_routes.py
Labels: docs

#476 fixed typing and added docs
  docsrc/modules/helperFunctions.compare_sets.rst
  docsrc/modules/helperFunctions.rst
  src/helperFunctions/compare_sets.py
  src/plugins/compare/file_coverage/code/file_coverage.py
  src/test/unit/helperFunctions/test_compare_sets.py
Labels: docs

#478 Sd1240 plugin doc js
  docsrc/README.md
  docsrc/conf.py
  docsrc/modules/helperFunctions.mongo_task_conversion.rst
  docsrc/modules/helperFunctions.rst
  src/helperFunctions/mongo_task_conversion.py
  src/test/acceptance/run_scripts/test_run_scripts.py
Labels: docs
