Repository fkie-cad/FACT_core, pull requests merged in 2020-09, with the labels that each got.

#484 setuptools 50 bugfix
  src/install/common.py
Labels: bug

#482 Document objects
  .pylintrc
  docsrc/index.rst
  docsrc/modules/objects.file.rst
  docsrc/modules/objects.rst
  src/helperFunctions/yara_binary_search.py
  src/intercom/back_end_binding.py
  src/objects/file.py
  src/storage/db_interface_backend.py
  src/storage/db_interface_common.py
  src/storage/fsorganizer.py
  src/test/acceptance/test_upload_analyze_delete_firmware.py
  src/test/integration/intercom/test_task_communication.py
  src/test/integration/scheduler/test_unpack_analyse_and_compare.py
  src/test/integration/scheduler/test_unpack_and_analyse.py
  src/test/integration/scheduler/test_unpack_only.py
  src/test/unit/objects/test_file.py
  src/test/unit/objects/test_firmware.py
  src/test/unit/storage/test_fs_organizer.py
  src/unpacker/unpack.py
Labels: docs, refactoring

#483 Sd1240 plugin doc js
  docsrc/modules/helperFunctions.database.rst
  docsrc/modules/helperFunctions.rst
  src/helperFunctions/database.py
  src/helperFunctions/mongo_task_conversion.py
  src/helperFunctions/statistic.py
  src/statistic/update.py
  src/test/integration/statistic/test_update.py
  src/test/unit/helperFunctions/test_database.py
  src/test/unit/helperFunctions/test_mongo_task_conversion.py
  src/test/unit/helperFunctions/test_statistic.py
  src/test/unit/statistic/test_update.py
Labels: docs, refactoring

#486 Sd1240 plugin doc js
  docsrc/modules/helperFunctions.process.rst
  docsrc/modules/helperFunctions.rst
  src/analysis/PluginBase.py
  src/helperFunctions/process.py
  src/intercom/back_end_binding.py
  src/test/unit/helperFunctions/test_process.py
Labels: docs

#491 Xenial test deprecation warning fix
  src/test/acceptance/run_scripts/test_run_scripts.py
Labels: bug

#495 fix cve feed link
  src/plugins/analysis/cve_lookup/internal/data_parsing.py
Labels: bug

#492 Sd1240 plugin doc js
  docsrc/modules/helperFunctions.logging.rst
  docsrc/modules/helperFunctions.rst
  src/compare/PluginBase.py
  src/helperFunctions/dependency.py
  src/helperFunctions/logging.py
  src/test/integration/scheduler/test_unpack_analyse_and_compare.py
  src/test/unit/compare/test_plugin_base.py
  src/test/unit/helperFunctions/test_dependency.py
Labels: docs

#488 Add route decorator
  src/test/unit/web_interface/test_app_show_analysis.py
  src/web_interface/components/analysis_routes.py
  src/web_interface/components/compare_routes.py
  src/web_interface/components/component_base.py
  src/web_interface/components/database_routes.py
  src/web_interface/components/miscellaneous_routes.py
Labels: enhancement, gui

#497 Sd1240 plugin doc js
  src/storage/db_interface_frontend.py
  src/test/integration/storage/test_db_interface_frontend.py
  src/test/unit/web_interface/test_file_tree.py
  src/web_interface/components/ajax_routes.py
  src/web_interface/file_tree/__init__.py
  src/web_interface/file_tree/file_tree.py
  src/web_interface/file_tree/file_tree_node.py
  src/web_interface/file_tree/jstree_conversion.py
Labels: docs

#489 Upload reanalyze template merge
  src/helperFunctions/web_interface.py
  src/intercom/back_end_binding.py
  src/intercom/front_end_binding.py
  src/test/common_helper.py
  src/test/unit/web_interface/test_app_re_analyze.py
  src/web_interface/components/analysis_routes.py
  src/web_interface/templates/macros.html
  src/web_interface/templates/upload/re-analyze.html
  src/web_interface/templates/upload/upload.html
Labels: refactoring
