Repository fkie-cad/FACT_core, pull requests merged in 2021-09, with the labels that each got.

#642 Fixed Codacy Badge
  README.md
Labels: bug, docs

#600 added checkbox to force single analysis update
  src/scheduler/Analysis.py
  src/test/unit/scheduler/test_analysis.py
  src/web_interface/components/analysis_routes.py
  src/web_interface/templates/about.html
  src/web_interface/templates/show_analysis.html
Labels: feature

#630 fixed navbar scaling for medium width
  src/web_interface/templates/base.html
Labels: bug, gui

#650 fixed incompatibility with newest highlight.js version
  src/web_interface/templates/show_analysis.html
Labels: bug

#648 navbar: on searchbar expansion, collapse navbar icons
  src/web_interface/static/js/quick_search.js
  src/web_interface/templates/base.html
Labels: bug, gui

#653 Hex preview
  src/install/requirements_frontend.txt
  src/intercom/back_end_binding.py
  src/intercom/common_mongo_binding.py
  src/intercom/front_end_binding.py
  src/storage/binary_service.py
  src/test/acceptance/test_authenticated_gui.py
  src/test/common_helper.py
  src/test/integration/intercom/test_backend_scheduler.py
  src/test/integration/intercom/test_task_communication.py
  src/test/integration/storage/test_binary_service.py
  src/test/unit/web_interface/test_app_ajax_routes.py
  src/test/unit/web_interface/test_app_show_analysis.py
  src/test/unit/web_interface/test_hex_highlighting.py
  src/web_interface/components/ajax_routes.py
  src/web_interface/components/hex_highlighting.py
  src/web_interface/static/js/line_numbering.js
  src/web_interface/templates/show_analysis.html
Labels: gui, feature
