Repository fkie-cad/FACT_core, pull requests merged in 2021-12, with the labels that each got.

#708 pin pymongo version
  src/install/requirements_common.txt
Labels: bug

#709 converted current analyses duplicate file warning loggings to debug
  src/scheduler/Analysis.py
  src/test/unit/scheduler/test_current_analyses.py
Labels: enhancement

#713 Moved introspection code
  src/scheduler/analysis.py
  src/scheduler/analysis_status.py
  src/start_fact_backend.py
  src/test/acceptance/base.py
  src/test/integration/scheduler/test_cycle_with_tags.py
  src/test/integration/scheduler/test_regression_virtual_file_path.py
  src/test/integration/scheduler/test_unpack_analyse_and_compare.py
  src/test/integration/scheduler/test_unpack_and_analyse.py
  src/test/unit/scheduler/test_analysis.py
  src/test/unit/scheduler/test_analysis_status.py
Labels: analysis, review requested

#719 Current analyses keyerror bugfix
  src/scheduler/Unpacking.py
  src/scheduler/analysis.py
  src/scheduler/analysis_status.py
  src/start_fact_backend.py
  src/test/unit/scheduler/test_analysis.py
  src/test/unit/scheduler/test_unpack.py
Labels: bug

#714 Created plugin to query circ.lu hashlookup API
  src/plugins/analysis/hashlookup/__init__.py
  src/plugins/analysis/hashlookup/code/__init__.py
  src/plugins/analysis/hashlookup/code/hashlookup.py
  src/plugins/analysis/hashlookup/test/__init__.py
  src/plugins/analysis/hashlookup/test/test_hashlookup.py
  src/plugins/mime_blacklists.py
Labels: analysis, feature, review requested

#715 Moved task scheduling code and documented analysis scheduler
  docsrc/index.rst
  docsrc/modules/scheduler.analysis.rst
  docsrc/modules/scheduler.rst
  src/compare/compare.py
  src/scheduler/Compare.py
  src/scheduler/analysis.py
  src/scheduler/analysis_status.py
  src/scheduler/task_scheduler.py
  src/test/unit/compare/test_compare.py
  src/test/unit/scheduler/test_analysis.py
  src/test/unit/scheduler/test_task_scheduler.py
Labels: refactoring, review requested

#721 fixed binwalk installation
  src/plugins/analysis/binwalk/code/binwalk.py
  src/plugins/analysis/binwalk/install.py
Labels: bug
