Repository fkie-cad/FACT_core, pull requests merged in 2021-07, with the labels that each got.

#596 fix unnecessary warnings in plugin system
  src/helperFunctions/plugin.py
Labels: bug

#597 frontend signal forwarding bugfix
  src/start_fact_frontend.py
Labels: bug

#593 lazy tags KeyError bugfix
  src/storage/db_interface_common.py
Labels: bug

#601 Document remaining helperFunctions
  docsrc/conf.py
  docsrc/modules/helperFunctions.config.rst
  docsrc/modules/helperFunctions.hash.rst
  docsrc/modules/helperFunctions.merge_generators.rst
  docsrc/modules/helperFunctions.object_conversion.rst
  docsrc/modules/helperFunctions.plugin.rst
  docsrc/modules/helperFunctions.program_setup.rst
  docsrc/modules/helperFunctions.rst
  src/fact_base.py
  src/helperFunctions/config.py
  src/helperFunctions/hash.py
  src/helperFunctions/merge_generators.py
  src/helperFunctions/object_conversion.py
  src/helperFunctions/plugin.py
  src/helperFunctions/program_setup.py
  src/init_database.py
  src/storage/db_interface_frontend.py
  src/test/unit/helperFunctions/test_merge_generators.py
  src/test/unit/helperFunctions/test_object_conversion.py
  src/update_statistic.py
  src/update_variety_data.py
Labels: docs

#608 Kernel config hardening check
  src/plugins/analysis/kernel_config/code/kernel_config.py
  src/plugins/analysis/kernel_config/install.sh
  src/plugins/analysis/kernel_config/internal/checksec_check_kernel.py
  src/plugins/analysis/kernel_config/internal/kernel_config_hardening_check.py
  src/plugins/analysis/kernel_config/test/test_kernel_config.py
  src/plugins/analysis/kernel_config/view/kernel_config.html
  src/test/unit/web_interface/test_filter.py
  src/web_interface/components/jinja_filter.py
  src/web_interface/filter.py
Labels: feature
