Repository fkie-cad/FACT_core, pull requests merged in 2023-01, with the labels that each got.

#947 Copyright, Social and bye-bye BCH
  README.md
  docsrc/conf.py
  src/check_signatures.py
  src/compile_yara_signatures.py
  src/flask_app_wrapper.py
  src/install.py
  src/start_fact.py
  src/start_fact_backend.py
  src/start_fact_db.py
  src/start_fact_frontend.py
  src/update_statistic.py
  src/version.py
  src/web_interface/templates/about.html
  src/web_interface/templates/base.html
Labels: docs

#946 removed some unused functions
  src/flask_app_wrapper.py
  src/helperFunctions/merge_generators.py
  src/storage/db_interface_common.py
  src/test/integration/storage/test_db_interface_common.py
Labels: refactoring

#951 fixed shutdown of analysis scheduler
  src/scheduler/analysis.py
Labels: bug

#952 ipc plugin summary bugfix
  src/plugins/analysis/ipc/code/ipc_analyzer.py
  src/plugins/analysis/ipc/test/test_ipc_analyzer.py
Labels: bug

#960 pinned versions of flask-wtf and setuptools
  src/install/requirements_common.txt
  src/install/requirements_frontend.txt
Labels: bug

#886 added analysis live stats
  docsrc/conf.py
  src/analysis/PluginBase.py
  src/scheduler/analysis.py
  src/statistic/analysis_stats.py
  src/test/unit/statistic/test_analysis_stats.py
  src/web_interface/static/js/system_health.js
  src/web_interface/templates/system_health.html
Labels: gui, feature

#963 missing files in file tree w/o root_uid fix
  src/web_interface/file_tree/file_tree.py
Labels: bug

#967 automated vagrant builds of our master branch available
  INSTALL.vagrant.md
  README.md
Labels: enhancement, feature, discussion needed

#968 update page plugin preset bugfix
  src/web_interface/components/analysis_routes.py
Labels: bug
